## นำเข้าข้อมูล

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

path = '/content/drive/My Drive/datavi'

In [ ]:
service_ip_66q4 = os.path.join(path,'opendata_02_service_ip_66q4.csv')
print(service_ip_66q4)

/content/drive/My Drive/datavi/opendata_02_service_ip_66q4.csv

In [ ]:
m = path + '/opendata_02_service_ip_66q4.csv'
print(m)

/content/drive/My Drive/datavi/opendata_02_service_ip_66q4.csv

##โหลด DATA

In [ ]:
df4 = pd.read_csv(m,dtype={'hcode': str, 'month_no': str})
df4

/tmp/ipykernel_1959/3576595975.py:1: DtypeWarning:

Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.

,month_no,hcode,hname,province_id,prov,nhso_zonename,gender,service_type,pdx,pdx_name,n_pop,n_service
0,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,L03,Cellulitis,1,1
1,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,I10,Essential (primary) hypertension,1,1
2,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,A09,Diarrhoea and gastroenteritis of presumed infe...,6,6
3,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1.0,IP,J18,Pneumonia organism unspecified,1,1
4,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,A41,Other septicaemia,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
514271,202309,SNC02,แผนกแพทย์ รร.ชุมพลฯ,SN00,กรมแพทย์ทหารเรือ,กรมแพทย์ทหาร,1.0,IP,J00,Acute nasopharyngitis [common cold],10,10
514272,202309,SNC05,กองพันพยาบาลกรมสนับสนุนหน่วยบัญชาการต่อสู้อากา...,SN00,กรมแพทย์ทหารเรือ,กรมแพทย์ทหาร,1.0,IP,Z76,Persons encountering health services in other ...,1,1
514273,202309,SNC05,กองพันพยาบาลกรมสนับสนุนหน่วยบัญชาการต่อสู้อากา...,SN00,กรมแพทย์ทหารเรือ,กรมแพทย์ทหาร,1.0,IP,F41,Other anxiety disorders,4,4
514274,202309,SNC05,กองพันพยาบาลกรมสนับสนุนหน่วยบัญชาการต่อสู้อากา...,SN00,กรมแพทย์ทหารเรือ,กรมแพทย์ทหาร,1.0,IP,F32,Depressive episodes,1,1
514275,202309,SNC09,รพ.ทหารเรือกรุงเทพ,SN00,กรมแพทย์ทหารเรือ,กรมแพทย์ทหาร,1.0,IP,F15,Mental and behavioral disorders due to use of ...,2,2

In [ ]:
df4.head()

,month_no,hcode,hname,province_id,prov,nhso_zonename,gender,service_type,pdx,pdx_name,n_pop,n_service
0,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,L03,Cellulitis,1,1
1,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,I10,Essential (primary) hypertension,1,1
2,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,A09,Diarrhoea and gastroenteritis of presumed infe...,6,6
3,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1.0,IP,J18,Pneumonia organism unspecified,1,1
4,202307,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,2.0,IP,A41,Other septicaemia,1,1

In [ ]:
df4.isnull().sum()

month_no            0
hcode               0
hname               0
province_id         0
prov                0
nhso_zonename       0
gender            112
service_type        0
pdx                 0
pdx_name         1674
n_pop               0
n_service           0
dtype: int64

In [ ]:
# 1. สร้างตารางจับคู่ (รหัสโรค -> ชื่อโรค) จากแถวที่ไม่เป็นค่าว่าง
pdx_dict = df4.dropna(subset=['pdx_name']).drop_duplicates(subset=['pdx']).set_index('pdx')['pdx_name'].to_dict()

# 2. อ่านรหัสโรคจากคอลัมน์ pdx แล้วเอาชื่อโรคมาเติมในช่อง pdx_name ที่ว่าง
df4['pdx_name'] = df4['pdx_name'].fillna(df4['pdx'].map(pdx_dict))

In [ ]:
df4.isnull().sum()

month_no            0
hcode               0
hname               0
province_id         0
prov                0
nhso_zonename       0
gender            112
service_type        0
pdx                 0
pdx_name         1674
n_pop               0
n_service           0
dtype: int64

In [ ]:
print(f"Original number of rows: {len(df4)}")
df4.dropna(inplace=True)
print(f"Number of rows after dropping nulls: {len(df4)}")

Original number of rows: 514276
Number of rows after dropping nulls: 512490

In [ ]:
# แปลงรหัสเพศให้เป็นชื่อที่อ่านเข้าใจง่าย (1: ชาย, 2: หญิง, อื่นๆ: ไม่ระบุ)
df4['gender'] = df4['gender'].fillna(0)
gender_map = {1.0: 'ชาย', 2.0: 'หญิง', 0: 'ไม่ระบุ'}
df4['gender_label'] = df4['gender'].map(gender_map)

## Top 5 ผู้ป่วยที่เข้ารับบริการส่วนมากเข้ามารับบริการเพราะโรคใด

In [ ]:
# 3. สร้างกราฟแท่งแนวตั้งแสดงโรคที่เด่นที่สุด 10 อันดับแรกพร้อมเปอร์เซ็นต์สัดส่วน
top10_disease = df_disease.head(5)

fig = px.bar(
    top10_disease,
    x='n_service',
    y='pdx_name',
    orientation='h',
    text=top10_disease.apply(lambda r: f"{r['n_service']:,} ครั้ง ({r['percentage']:.2f}%)", axis=1),
    color='n_service',
    color_continuous_scale='Reds',
    title='5 อันดับโรค/อาการที่เด่นที่สุดและมีสัดส่วนผู้เข้าใช้บริการสูงที่สุด (Top Dominant Diseases)',
    labels={'pdx_name': 'ชื่อโรค / อาการ', 'n_service': 'จำนวนครั้งการให้บริการ'}
)

fig.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_title="จำนวนครั้งการเข้ารับบริการ (ครั้ง)",
    yaxis_title="",
    coloraxis_showscale=False,
    height=550,
    margin=dict(l=150, r=50, t=80, b=50)
)

fig.update_traces(textposition='inside', textfont=dict(color='white', size=11))
fig.show()

## ใช้ Treemap สำหรับแสดงสัดส่วนของโรคจำแนกตามภูมิภาค

In [ ]:
import plotly.express as px

# ป้องกัน KeyError: สร้างหรือแมปคอลัมน์ region ใหม่ให้ถูกต้องเรียบร้อยก่อน
if 'region_map' in globals():
    df4['region'] = df4['prov'].map(region_map)
else:
    from code_context import region_map
    df4['region'] = df4['prov'].map(region_map)

df4['region'] = df4['region'].fillna('ภาคกลาง')

# 1. จัดกลุ่มข้อมูลตามภูมิภาคและชื่อโรค
df_region_disease = df4.groupby(['region', 'pdx_name'], as_index=False)['n_service'].sum()

# 2. ดึง Top 5 โรคของแต่ละภูมิภาค
top_diseases_per_region = df_region_disease.sort_values(['region', 'n_service'], ascending=[True, False]).groupby('region').head(5).reset_index(drop=True)

# 3. สร้าง Treemap
fig = px.treemap(
    top_diseases_per_region,
    path=['region', 'pdx_name'],
    values='n_service',
    color='n_service',
    color_continuous_scale='Purples',  # เปลี่ยนเป็น Purples หรือ Plasma เพื่อความเข้มและชัดเจนขึ้น
    title='Treemap แสดงสัดส่วนโรคเด่น 5 อันดับแรกจำแนกตามภูมิภาค (ภูมิภาค -> ชื่อโรค)',
    labels={'region': 'ภูมิภาค', 'pdx_name': 'ชื่อโรค/อาการ', 'n_service': 'จำนวนครั้งการบริการ'}
)

# 4. ปรับแต่งการแสดงผลและสีข้อความให้ชัดเจน (แก้ปัญหาสีกลืน)
fig.update_traces(
    root_color="#f0f2f5",
    textinfo="label+value+percent parent",
    # เอา color="white" ออกเพื่อให้ Plotly ปรับสีตัวอักษร (ดำ/ขาว) ตามความสว่างพื้นหลังอัตโนมัติ
    textfont=dict(size=13, family="Tohoma, Sans-serif"),
    marker=dict(
        line=dict(color='white', width=2)  # เพิ่มเส้นขอบขาวแยกแต่ละบล็อกให้ดูง่ายขึ้น
    ),
    hovertemplate="""
<b>ระดับชั้น:</b> %{label}<br>
<b>จำนวนครั้งการให้บริการ:</b> %{value:,} ครั้ง<br>
<b>สัดส่วนจากกลุ่มหลัก:</b> %{percentParent:.2%}<br>
<b>สัดส่วนจากทั้งหมด:</b> %{percentRoot:.2%}
<extra></extra>
"""
)

fig.update_layout(
    margin=dict(t=60, l=10, r=10, b=10),
    height=750,
    font=dict(size=12),
    coloraxis_colorbar=dict(
        title="จำนวนครั้ง",
        thickness=15,
        len=0.8
    )
)

fig.show()

##ใช้ Marimekko Chart สำหรับแสดงความสัมพันธ์ระหว่างโรคและเพศ

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

# 1. กรองเฉพาะ Top 10 โรคที่มีผู้ใช้บริการสูงสุดเพื่อไม่ให้กราฟหนาแน่นเกินไป
top10_pdx = df4.groupby('pdx_name')['n_service'].sum().nlargest(10).index
df_filtered = df4[df4['pdx_name'].isin(top10_pdx)]

# 2. คำนวณสรุปข้อมูลแยกตาม โรค และ เพศ
df_grouped_pdx = df_filtered.groupby(['pdx_name', 'gender_label'])['n_service'].sum().unstack(fill_value=0)

# หาผลรวมของแต่ละโรค และสัดส่วนสะสมเพื่อเรียงลำดับจากมากไปน้อย
pdx_totals = df_grouped_pdx.sum(axis=1)
total_pdx_services = pdx_totals.sum()
pdx_shares = (pdx_totals / total_pdx_services).sort_values(ascending=False)

# เรียงลำดับข้อมูล
df_grouped_pdx = df_grouped_pdx.reindex(pdx_shares.index)
df_percentage_pdx = df_grouped_pdx.div(df_grouped_pdx.sum(axis=1), axis=0) * 100

# 3. คำนวณตำแหน่งแกน X และความกว้าง
widths_pdx = pdx_shares.values * 100
x_positions_pdx = np.cumsum(widths_pdx) - (widths_pdx / 2)

# 4. สร้าง Marimekko Chart
fig = go.Figure()
genders = ['ชาย', 'หญิง', 'ไม่ระบุ']
colors_map = {'ชาย': '#3182bd', 'หญิง': '#e377c2', 'ไม่ระบุ': '#7f7f7f'}

for g in genders:
    if g in df_percentage_pdx.columns:
        fig.add_trace(go.Bar(
            name=g,
            x=x_positions_pdx,
            y=df_percentage_pdx[g],
            width=widths_pdx,
            offset=-(widths_pdx / 2),
            marker=dict(color=colors_map.get(g, '#7f7f7f'), line=dict(color='white', width=1.5)),
            customdata=np.stack([
                df_grouped_pdx[g],
                [pdx_totals[p] for p in df_grouped_pdx.index],
                [pdx_shares[p] * 100 for p in df_grouped_pdx.index]
            ], axis=-1),
            hovertemplate=(
                "<b>โรค:</b> %{x_label}<br>" +
                "<b>เพศ:</b> " + g + "<br>" +
                "<b>สัดส่วนเพศในโรคนี้:</b> %{y:.1f}%<br>" +
                "<b>จำนวนการรักษาเฉพาะเพศ:</b> %{customdata[0]:,} ครั้ง<br>" +
                "<b>จำนวนรวมของโรคนี้:</b> %{customdata[1]:,} ครั้ง<br>" +
                "<b>ส่วนแบ่งของโรคนี้ใน Top 10:</b> %{customdata[2]:.1f}%<br>" +
                "<extra></extra>"
            )
        ))

fig.update_layout(
    barmode='stack',
    title=dict(
        text='Marimekko Chart: สัดส่วนเพศและขนาดจำนวนการรักษาจำแนกตามกลุ่มโรค (Top 10)<br><sup>(ความกว้างสะท้อนสัดส่วนผู้เข้ารับรักษาของแต่ละโรค / ความสูงสะท้อนสัดส่วนเพศภายในโรคนั้น)</sup>',
        x=0.5
    ),
    xaxis=dict(
        title='สัดส่วนการใช้บริการสะสมของกลุ่มโรคหลัก (%)',
        tickvals=list(np.linspace(0, 100, 11)),
        ticktext=[f'{int(val)}%' for val in np.linspace(0, 100, 11)]
    ),
    yaxis=dict(
        title='สัดส่วนของแต่ละเพศ (%)',
        ticksuffix='%'
    ),
    legend_title='เพศ',
    height=750,
    width=1150,
    margin=dict(t=160, b=150, l=80, r=40)
)

# ปรับป้ายกำกับชื่อโรคด้านบนเพื่อป้องกันการซ้อนเบียด
for pdx, x_pos, width in zip(df_grouped_pdx.index, x_positions_pdx, widths_pdx):
    # ตัดคำสั้นลงเพื่อความกระชับและไม่เบียดเสียด
    short_name = pdx[:20] + '...' if len(pdx) > 20 else pdx
    fig.add_annotation(
        x=x_pos,
        y=105,
        text=f"<b>{short_name}</b><br>({width:.1f}%)",
        showarrow=False,
        font=dict(size=8.5, color='black'),
        align='center',
        textangle=-30 # เอียงองศาเพิ่มขึ้นเพื่อหลบเลี่ยงการซ้อนทับอย่างมีประสิทธิภาพ
    )

fig.show()

#### **สร้างคอลัมน์ภูมิภาคจากข้อมูลจังหวัด**
แสดงกราฟข้อมูลจากภูมิภาคไปเขต

In [ ]:
# กำหนดจังหวัดในแต่ละภูมิภาค
region_map = {
    # ภาคเหนือ
    'เชียงใหม่': 'ภาคเหนือ',
    'เชียงราย': 'ภาคเหนือ',
    'ลำปาง': 'ภาคเหนือ',
    'ลำพูน': 'ภาคเหนือ',
    'แม่ฮ่องสอน': 'ภาคเหนือ',
    'น่าน': 'ภาคเหนือ',
    'พะเยา': 'ภาคเหนือ',
    'แพร่': 'ภาคเหนือ',
    'อุตรดิตถ์': 'ภาคเหนือ',
    'พิษณุโลก': 'ภาคเหนือ',
    'สุโขทัย': 'ภาคเหนือ',

    # ภาคตะวันออกเฉียงเหนือ
    'ขอนแก่น': 'ภาคตะวันออกเฉียงเหนือ',
    'อุดรธานี': 'ภาคตะวันออกเฉียงเหนือ',
    'เลย': 'ภาคตะวันออกเฉียงเหนือ',
    'หนองคาย': 'ภาคตะวันออกเฉียงเหนือ',
    'หนองบัวลำภู': 'ภาคตะวันออกเฉียงเหนือ',
    'บึงกาฬ': 'ภาคตะวันออกเฉียงเหนือ',
    'สกลนคร': 'ภาคตะวันออกเฉียงเหนือ',
    'นครพนม': 'ภาคตะวันออกเฉียงเหนือ',
    'มุกดาหาร': 'ภาคตะวันออกเฉียงเหนือ',
    'กาฬสินธุ์': 'ภาคตะวันออกเฉียงเหนือ',
    'มหาสารคาม': 'ภาคตะวันออกเฉียงเหนือ',
    'ร้อยเอ็ด': 'ภาคตะวันออกเฉียงเหนือ',
    'ยโสธร': 'ภาคตะวันออกเฉียงเหนือ',
    'อำนาจเจริญ': 'ภาคตะวันออกเฉียงเหนือ',
    'นครราชสีมา': 'ภาคตะวันออกเฉียงเหนือ',
    'ชัยภูมิ': 'ภาคตะวันออกเฉียงเหนือ',
    'บุรีรัมย์': 'ภาคตะวันออกเฉียงเหนือ',
    'สุรินทร์': 'ภาคตะวันออกเฉียงเหนือ',
    'ศรีสะเกษ': 'ภาคตะวันออกเฉียงเหนือ',
    'อุบลราชธานี': 'ภาคตะวันออกเฉียงเหนือ',

    # ภาคกลาง
    'กรุงเทพมหานคร': 'ภาคกลาง',
    'กรุงเทพฯ': 'ภาคกลาง',
    'นครปฐม': 'ภาคกลาง',
    'นนทบุรี': 'ภาคกลาง',
    'ปทุมธานี': 'ภาคกลาง',
    'สมุทรปราการ': 'ภาคกลาง',
    'สมุทรสาคร': 'ภาคกลาง',
    'สมุทรสงคราม': 'ภาคกลาง',
    'พระนครศรีอยุธยา': 'ภาคกลาง',
    'อ่างทอง': 'ภาคกลาง',
    'ลพบุรี': 'ภาคกลาง',
    'สิงห์บุรี': 'ภาคกลาง',
    'ชัยนาท': 'ภาคกลาง',
    'สระบุรี': 'ภาคกลาง',
    'นครสวรรค์': 'ภาคกลาง',
    'อุทัยธานี': 'ภาคกลาง',
    'กำแพงเพชร': 'ภาคกลาง',
    'พิจิตร': 'ภาคกลาง',
    'เพชรบูรณ์': 'ภาคกลาง',
    'สุพรรณบุรี': 'ภาคกลาง',
    'นครนายก': 'ภาคกลาง',

    # ภาคตะวันออก
    'ชลบุรี': 'ภาคตะวันออก',
    'ระยอง': 'ภาคตะวันออก',
    'จันทบุรี': 'ภาคตะวันออก',
    'ตราด': 'ภาคตะวันออก',
    'ฉะเชิงเทรา': 'ภาคตะวันออก',
    'ปราจีนบุรี': 'ภาคตะวันออก',
    'สระแก้ว': 'ภาคตะวันออก',

    # ภาคตะวันตก
    'กาญจนบุรี': 'ภาคตะวันตก',
    'ราชบุรี': 'ภาคตะวันตก',
    'เพชรบุรี': 'ภาคตะวันตก',
    'ประจวบคีรีขันธ์': 'ภาคตะวันตก',
    'ตาก': 'ภาคตะวันตก',

    # ภาคใต้
    'ชุมพร': 'ภาคใต้',
    'ระนอง': 'ภาคใต้',
    'สุราษฎร์ธานี': 'ภาคใต้',
    'พังงา': 'ภาคใต้',
    'ภูเก็ต': 'ภาคใต้',
    'กระบี่': 'ภาคใต้',
    'นครศรีธรรมราช': 'ภาคใต้',
    'ตรัง': 'ภาคใต้',
    'พัทลุง': 'ภาคใต้',
    'สตูล': 'ภาคใต้',
    'สงขลา': 'ภาคใต้',
    'ปัตตานี': 'ภาคใต้',
    'ยะลา': 'ภาคใต้',
    'นราธิวาส': 'ภาคใต้'
}

# สร้างคอลัมน์ภูมิภาคจากจังหวัด
df4['region'] = df4['prov'].map(region_map)


# =========================================================
# จัดกลุ่มข้อมูลกรมแพทย์ทหารเข้า "ภูมิภาค"
# =========================================================

# กรมแพทย์ทหารเรือ
# รพ.ทหารเรือกรุงเทพ → ภาคกลาง
df4.loc[
    (df4['prov'] == 'กรมแพทย์ทหารเรือ') &
    (df4['hname'].str.contains('รพ.ทหารเรือกรุงเทพ', na=False)),
    'region'
] = 'ภาคกลาง'

# หน่วยกรมแพทย์ทหารเรือที่อยู่ชลบุรี → ภาคตะวันออก
df4.loc[
    (df4['prov'] == 'กรมแพทย์ทหารเรือ') &
    (df4['hname'].str.contains(
        'ศูนย์ฝึกทหารใหม่|รร.ชุมพลฯ|กองพันพยาบาลกรมสนับสนุนหน่วยบัญชาการต่อสู้อากาศยาน',
        na=False
    )),
    'region'
] = 'ภาคตะวันออก'

# หน่วยที่เกี่ยวข้องกับจันทบุรีและตราด → ภาคตะวันออก
df4.loc[
    (df4['prov'] == 'กรมแพทย์ทหารเรือ') &
    (df4['hname'].str.contains('จันทบุรีและตราด', na=False)),
    'region'
] = 'ภาคตะวันออก'


# กรมแพทย์ทหารอากาศ
# รพ.จันทรุเบกษา → ภาคกลาง
df4.loc[
    (df4['prov'] == 'กรมแพทย์ทหารอากาศ') &
    (df4['hname'].str.contains('รพ.จันทรุเบกษา', na=False)),
    'region'
] = 'ภาคกลาง'


# =========================================================
# ตรวจสอบผล
# =========================================================

print("===== ตรวจสอบข้อมูลที่ยังไม่มีภูมิภาค =====")

missing_region = df4[df4['region'].isna()]

print("จำนวนข้อมูลที่ยังไม่มีภูมิภาค:", len(missing_region))

if len(missing_region) > 0:
    display(
        missing_region[
            ['prov', 'hname', 'hcode', 'region']
        ].drop_duplicates()
    )

print("\n===== จำนวนข้อมูลในแต่ละภูมิภาค =====")

display(
    df4['region']
    .value_counts(dropna=False)
    .rename_axis('region')
    .reset_index(name='count')
)

===== ตรวจสอบข้อมูลที่ยังไม่มีภูมิภาค =====
จำนวนข้อมูลที่ยังไม่มีภูมิภาค: 0

===== จำนวนข้อมูลในแต่ละภูมิภาค =====

                  region   count
0  ภาคตะวันออกเฉียงเหนือ  181955
1                ภาคกลาง  118085
2                 ภาคใต้   79761
3               ภาคเหนือ   70383
4            ภาคตะวันออก   35233
5             ภาคตะวันตก   27073

In [ ]:
print("การกระจายของข้อมูลตามภูมิภาค:")
display(df4['region'].value_counts())

การกระจายของข้อมูลตามภูมิภาค:

region
ภาคตะวันออกเฉียงเหนือ    181955
ภาคกลาง                  118136
ภาคใต้                    79761
ภาคเหนือ                  70383
ภาคตะวันออก               35182
ภาคตะวันตก                27073
Name: count, dtype: int64

In [ ]:
prov_to_region = {prov: region for region, provs in region_mapping.items() for prov in provs}
df4['region'] = df4['prov'].map(prov_to_region)

In [ ]:
import plotly.express as px

# 3. จัดกลุ่มข้อมูลเฉพาะ 2 ระดับ (ภูมิภาค -> เขต สปสช.)
df_tree = df4.groupby(['region', 'nhso_zonename'], as_index=False)['n_service'].sum()

# 4. สร้าง Treemap (2 ชั้น)
fig = px.treemap(
    df_tree,
    path=['region', 'nhso_zonename'], # ปรับเหลือ 2 ระดับ
    values='n_service',
    color='n_service',
    color_continuous_scale='Blues',
    title='Treemap แสดงสัดส่วนการใช้บริการสุขภาพ (ภูมิภาค -> เขต สปสช.)'
)

fig.update_traces(root_color="lightgrey")
fig.update_layout(margin=dict(t=50, l=10, r=10, b=10))

# แสดงผลแผนภูมิ
fig.show()

#ภูมิภาคไหนที่มีคนเข้าใช้บริการบ่อยที่สุด

In [ ]:
import plotly.express as px

# คำนวณสรุปจำนวนครั้งการรับบริการตามภูมิภาคจาก df4
df_region = df4.groupby('region')['n_service'].sum().reset_index()

# เรียงลำดับจากมากไปน้อย
df_region = df_region.sort_values(by='n_service', ascending=False)

# สร้างกราฟแท่ง
fig = px.bar(
    df_region,
    x='region',
    y='n_service',
    text='n_service',
    color='n_service',
    color_continuous_scale='Blues',
    title='จำนวนการเข้าใช้บริการสุขภาพจำแนกตามภูมิภาค',
    labels={'region': 'ภูมิภาค', 'n_service': 'จำนวนครั้งรับบริการ'}
)
fig.update_traces(texttemplate='%{text:,}', textposition='outside')
fig.update_layout(xaxis={'categoryorder':'total descending'})
fig.show()

#### **แสดงเขตไปจังหวัด**

In [ ]:
# 2. สรุปยอดข้อมูล 2 ระดับ (เขต สปสช. -> จังหวัด)
df_tree = df4.groupby(['nhso_zonename', 'prov'], as_index=False)['n_service'].sum()

# 3. สร้าง Treemap (เขต สปสช. -> จังหวัด)
fig = px.treemap(
    df_tree,
    path=['nhso_zonename', 'prov'],    # ลำดับชั้น Hierarchy (เขต สปสช. -> จังหวัด)
    values='n_service',                 # ขนาดบล็อกตามจำนวนการบริการ
    color='n_service',                  # ความเข้มสีตามจำนวนบริการ
    color_continuous_scale='Blues',     # ชุดสีโทนฟ้า
    title='Treemap แสดงสัดส่วนการใช้บริการสุขภาพ (เขต สปสช. -> จังหวัด)'
)

# 4. ปรับแต่งและแสดงผล
fig.update_traces(root_color="lightgrey")
fig.update_layout(margin=dict(t=50, l=10, r=10, b=10))

# แสดงผลบน Notebook
fig.show()

จากแผนภูมิวงกลมด้านบน เราสามารถเห็นสัดส่วนการใช้บริการในแต่ละภูมิภาคได้อย่างชัดเจน ภูมิภาคที่มีพื้นที่ใหญ่และประชากรหนาแน่น เช่น ภาคกลาง มักจะมีสัดส่วนผู้ใช้บริการที่สูงกว่าภูมิภาคอื่นๆ ซึ่งสอดคล้องกับข้อมูลทางภูมิศาสตร์และการกระจายตัวของประชากรในประเทศไทย

##เพศชายหญิง

In [ ]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

# 1. เตรียมและคำนวณข้อมูลสำหรับ Marimekko Chart
# หาจำนวนรวมของบริการแบ่งตาม ภูมิภาค และ เพศ
df_grouped = df4.groupby(['region', 'gender_label'])['n_service'].sum().unstack(fill_value=0)

# หาผลรวมบริการรวมของแต่ละภูมิภาค และ สัดส่วนรวมของแต่ละภูมิภาคในประเทศ
region_totals = df_grouped.sum(axis=1)
total_services = region_totals.sum()
region_shares = (region_totals / total_services).sort_values(ascending=False)

# เรียงลำดับภูมิภาคตามขนาดจำนวนครั้งรับบริการจากมากไปน้อย
df_grouped = df_grouped.reindex(region_shares.index)

# แปลงข้อมูลจำนวนบริการในแต่ละภูมิภาคให้เป็นเปอร์เซ็นต์ (สัดส่วน 100% ภายในกลุ่ม)
df_percentage = df_grouped.div(df_grouped.sum(axis=1), axis=0) * 100

# 2. คำนวณตำแหน่งและสเกลความกว้างของแต่ละแท่งบนแกน X
widths = region_shares.values * 100  # แปลงสัดส่วนความกว้างเป็น % 0-100
x_positions = np.cumsum(widths) - (widths / 2)  # จุดกึ่งกลางของแต่ละแท่งสำหรับวางป้ายชื่อ

# 3. สร้างกราฟ Marimekko โดยใช้ go.Bar
fig = go.Figure()

# เพิ่มแท่งกราฟสำหรับแต่ละเพศ
genders = df_percentage.columns
colors = {'ชาย': '#3182bd', 'หญิง': '#e377c2', 'ไม่ระบุ': '#7f7f7f'}  # กำหนดโทนสี

for gender in genders:
    fig.add_trace(go.Bar(
        name=gender,
        x=x_positions,
        y=df_percentage[gender],
        width=widths, # กำหนดความกว้างของแท่งตามส่วนแบ่งของภูมิภาค
        offset=-(widths/2), # จัดแนวให้อยู่ตรงกลางตำแหน่ง x
        marker=dict(color=colors.get(gender, '#bcbd22'), line=dict(color='white', width=1.5)),
        customdata=np.stack([
            df_grouped[gender],
            [region_totals[r] for r in df_grouped.index],
            [region_shares[r]*100 for r in df_grouped.index]
        ], axis=-1),
        hovertemplate=(
            "<b>ภูมิภาค:</b> %{x_label}<br>" +
            "<b>เพศ:</b> " + gender + "<br>" +
            "<b>สัดส่วนเพศในภูมิภาคนี้:</b> %{y:.1f}%<br>" +
            "<b>จำนวนบริการเฉพาะเพศนี้:</b> %{customdata[0]:,}<br>" +
            "<b>บริการทั้งหมดของภูมิภาคนี้:</b> %{customdata[1]:,}<br>" +
            "<b>ส่วนแบ่งของภูมิภาคในประเทศ:</b> %{customdata[2]:.1f}%<br>" +
            "<extra></extra>"
        )
    ))

# 4. ตั้งค่าหน้าตากราฟและแสดงผล
fig.update_layout(
    barmode='stack',
    title=dict(
        text='Marimekko Chart: สัดส่วนเพศและขนาดจำนวนผู้รับบริการจำแนกตามภูมิภาค<br><sup>(ความกว้างแท่งสะท้อนส่วนแบ่งผู้รับบริการของแต่ละภูมิภาค / ความสูงสะท้อนสัดส่วนเพศในภูมิภาคนั้น)</sup>',
        x=0.5
    ),
    xaxis=dict(
        title='สัดส่วนจำนวนบริการสะสมของภูมิภาค (%)',
        tickvals=list(np.linspace(0, 100, 11)),
        ticktext=[f'{int(val)}%' for val in np.linspace(0, 100, 11)]
    ),
    yaxis=dict(
        title='สัดส่วนของเพศ (%)',
        ticksuffix='%'
    ),
    legend_title='เพศ',
    height=700,
    width=1100,
    margin=dict(t=140, b=100, l=80, r=40)
)

# เพิ่มป้ายชื่อภูมิภาคที่แกน X ด้านบนตัวกราฟแบบเฉียงเพื่อกันตัวหนังสือเบียดกัน
for region, x_pos, width in zip(df_grouped.index, x_positions, widths):
    fig.add_annotation(
        x=x_pos,
        y=105,
        text=f"<b>{region}</b><br>({width:.1f}%)",
        showarrow=False,
        font=dict(size=10, color='black'),
        align='center',
        textangle=-15 # เอียงหลบเพื่อป้องกันตัวหนังสือซ้อนกัน
    )

fig.show()

In [ ]:
import pandas as pd
import plotly.express as px

# หา 5 อันดับแรกของโรงพยาบาลที่มีจำนวนครั้งการบริการสูงสุด
top5_hospitals = df4.groupby('hname')['n_service'].sum().nlargest(5).reset_index()

# แสดงเป็นกราฟแท่งเพื่อให้อ่านง่าย
fig = px.bar(
    top5_hospitals,
    x='n_service',
    y='hname',
    orientation='h',
    text='n_service',
    color='n_service',
    color_continuous_scale='Blues',
    title='5 อันดับโรงพยาบาลที่มีจำนวนครั้งการให้บริการสูงสุด',
    labels={'n_service': 'จำนวนครั้งการให้บริการ', 'hname': 'ชื่อโรงพยาบาล'}
)

fig.update_traces(texttemplate='%{text:,}', textposition='outside')
fig.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_title="จำนวนครั้งการให้บริการ",
    yaxis_title="",
    coloraxis_showscale=False,
    margin=dict(l=250, r=50, t=80, b=50)
)
fig.show()

In [ ]:
# ดึงข้อมูล 5 อันดับแรกที่มีจำนวนครั้งการบริการ (n_service) สูงที่สุด
top5_cases = df4.nlargest(5, 'n_service')[['month_no', 'hname', 'prov', 'gender_label', 'pdx_name', 'n_service']]

print("ข้อมูล 5 กลุ่มผู้เข้าใช้บริการ (หรือ 5 ราย) ที่มีจำนวนครั้งการเข้าใช้บริการสูงสุด:")
display(top5_cases.style.format({'n_service': '{:,}'}))

ข้อมูล 5 กลุ่มผู้เข้าใช้บริการ (หรือ 5 ราย) ที่มีจำนวนครั้งการเข้าใช้บริการสูงสุด:

##ใช้ Nightingale Rose Chart สำหรับแสดงการกระจายของผู้ป่วยในแต่ละเดือน

In [ ]:
import plotly.express as px
import pandas as pd

# 1. จัดกลุ่มข้อมูลตาม เดือน (month_no) และ เพศ (gender_label) เพื่อหาผลรวมจำนวนบริการ
df_monthly_gender = df4.groupby(['month_no', 'gender_label'])['n_service'].sum().reset_index()

# 2. แปลงรหัสเดือนให้เป็นชื่อเดือนที่เข้าใจง่าย
month_map = {
    '202307': 'กรกฎาคม 2023',
    '202308': 'สิงหาคม 2023',
    '202309': 'กันยายน 2023'
}
df_monthly_gender['month_name'] = df_monthly_gender['month_no'].astype(str).map(month_map).fillna(df_monthly_gender['month_no'])

# เรียงลำดับข้อมูลตามรหัสเดือน
df_monthly_gender = df_monthly_gender.sort_values('month_no')

# 3. สร้าง Rose Chart (Polar Bar Chart) โดยใช้ px.bar_polar และแก้ barmode เป็น 'stack'
fig = px.bar_polar(
    df_monthly_gender,
    r='n_service',
    theta='month_name',
    color='gender_label',
    color_discrete_map={'ชาย': '#3182bd', 'หญิง': '#e377c2', 'ไม่ระบุ': '#7f7f7f'},
    barmode='stack',
    title='จำนวนการเข้าใช้บริการจำแนกตามเพศในแต่ละเดือน',
    labels={'n_service': 'จำนวนครั้งการให้บริการ', 'month_name': 'เดือน', 'gender_label': 'เพศ'}
)

# ปรับแต่งการแสดงผลและป้ายข้อความ
fig.update_layout(
    polar=dict(
        angularaxis=dict(direction='clockwise', period=len(df_monthly_gender['month_name'].unique())),
        radialaxis=dict(ticksuffix='', angle=45)
    ),
    font=dict(size=12),
    height=600,
    width=800
)

fig.show()

##ใช้ Stacked Area Chart สำหรับเปรียบเทียบแนวโน้มของโรคในแต่ละภูมิภาค

In [ ]:
import plotly.express as px
import pandas as pd

# 1. หา Top 5 โรคที่มีจำนวนการบริการสูงที่สุดในภาพรวม
top_diseases = df4.groupby('pdx_name')['n_service'].sum().nlargest(5).index

# 2. กรองข้อมูลเฉพาะ Top 5 โรคนี้ และจัดกลุ่มตามภูมิภาคและโรค
df_filtered = df4[df4['pdx_name'].isin(top_diseases)]
df_area = df_filtered.groupby(['region', 'pdx_name'], as_index=False)['n_service'].sum()

# เรียงลำดับภูมิภาคเพื่อให้แกน X เรียงตัวสวยงาม
region_order = ['เหนือ', 'ตะวันออกเฉียงเหนือ', 'กลาง', 'ตะวันออก', 'ตะวันตก', 'ใต้', 'อื่น ๆ']
df_area['region'] = pd.Categorical(df_area['region'], categories=region_order, ordered=True)
df_area = df_area.sort_values('region')

# 3. สร้าง Stacked Area Chart
fig = px.area(
    df_area,
    x='region',
    y='n_service',
    color='pdx_name',
    title='Stacked Area Chart: เปรียบเทียบจำนวนการบริการของโรคหลักจำแนกตามภูมิภาค',
    labels={'region': 'ภูมิภาค', 'n_service': 'จำนวนครั้งการให้บริการ', 'pdx_name': 'โรค/อาการ'},
    color_discrete_sequence=px.colors.qualitative.Safe
)

fig.update_layout(
    xaxis_title='ภูมิภาค',
    yaxis_title='จำนวนครั้งการให้บริการ (ครั้ง)',
    hovermode='x unified',
    legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
)

fig.show()

### วิเคราะห์หาชื่อโรค/อาการที่โดดเด่นและมีผู้เข้าใช้บริการมากที่สุด

In [ ]:
import pandas as pd
import plotly.express as px

# 1. จัดกลุ่มและคำนวณผลรวมจำนวนครั้งการรับบริการ (n_service) แยกตามชื่อโรค (pdx_name)
df_disease = df4.groupby('pdx_name')['n_service'].sum().reset_index()

# 2. เรียงลำดับจากมากไปน้อย และคำนวณสัดส่วนสะสม (% Share)
total_all_services = df_disease['n_service'].sum()
df_disease['percentage'] = (df_disease['n_service'] / total_all_services) * 100
df_disease = df_disease.sort_values(by='n_service', ascending=False).reset_index(drop=True)

# ดึง Top 15 โรค/อาการที่เด่นที่สุด
top15_disease = df_disease.head(15)

# แสดงตารางวิเคราะห์
print("ตารางแสดง 15 อันดับโรค/อาการที่เด่นที่สุด (มีสัดส่วนผู้รับบริการสูงที่สุด):")
display(top15_disease.style.format({'n_service': '{:,}', 'percentage': '{:.2f}%'}))

ตารางแสดง 15 อันดับโรค/อาการที่เด่นที่สุด (มีสัดส่วนผู้รับบริการสูงที่สุด):

In [ ]:
import plotly.graph_objects as go

# เรียงจากน้อย → มาก
df_lollipop = top15_disease.sort_values('n_service').copy()

# สีพาสเทล 15 สี
pastel_colors = [
    '#A8D8EA',  # ฟ้า
    '#F7B7D2',  # ชมพู
    '#B8E0D2',  # เขียวมิ้นต์
    '#FFD6A5',  # ส้มอ่อน
    '#CDB4DB',  # ม่วง
    '#FFF1A8',  # เหลือง
    '#AFCBFF',  # น้ำเงินอ่อน
    '#FFB7B2',  # แดงพาสเทล
    '#BDE0FE',  # ฟ้าอ่อน
    '#CDEAC0',  # เขียวอ่อน
    '#E2C2FF',  # ม่วงอ่อน
    '#FFD1DC',  # ชมพูอ่อน
    '#B5EAD7',  # เขียวมิ้นต์อ่อน
    '#FFDAC1',  # พีช
    '#D7BDE2'   # ม่วงลาเวนเดอร์
]

fig = go.Figure()

# วาดเส้นและจุดของแต่ละโรค
for i, (_, row) in enumerate(df_lollipop.iterrows()):

    # เส้น
    fig.add_trace(
        go.Scatter(
            x=[0, row['n_service']],
            y=[row['pdx_name'], row['pdx_name']],
            mode='lines',
            line=dict(
                color=pastel_colors[i],
                width=5
            ),
            showlegend=False,
            hoverinfo='skip'
        )
    )

    # จุด
    fig.add_trace(
        go.Scatter(
            x=[row['n_service']],
            y=[row['pdx_name']],
            mode='markers+text',
            marker=dict(
                size=15,
                color=pastel_colors[i],
                line=dict(
                    color='white',
                    width=2
                )
            ),
            text=[f"{row['n_service']:,}"],
            textposition='middle right',
            textfont=dict(
                size=11,
                color='#555555'
            ),
            showlegend=False,
            hovertemplate=(
                '<b>%{y}</b><br>'
                'จำนวนครั้งเข้ารับบริการ: %{x:,}'
                '<extra></extra>'
            )
        )
    )

fig.update_layout(
    title=dict(
        text='15 อันดับโรค/อาการที่มีจำนวนครั้งเข้ารับบริการสูงที่สุด',
        x=0.5
    ),
    xaxis_title='จำนวนครั้งเข้ารับบริการ',
    yaxis_title='โรค/อาการ',

    height=700,

    margin=dict(
        l=300,
        r=100,
        t=90,
        b=60
    ),

    plot_bgcolor='white',
    paper_bgcolor='white',

    xaxis=dict(
        showgrid=True,
        gridcolor='#EEEEEE'
    ),

    yaxis=dict(
        showgrid=False
    )
)

fig.show()