<a href="https://colab.research.google.com/github/kanokwantho/Project_Tonper/blob/main/DataIP66Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

path = '/content/drive/My Drive/dataIP'

In [10]:
service_ip_66q4 = os.path.join(path,'opendata_02_service_ip_66q1.csv')
print(service_ip_66q4)

/content/drive/My Drive/dataIP/opendata_02_service_ip_66q1.csv

In [11]:
m = path + '/opendata_02_service_ip_66q1.csv'
print(m)

/content/drive/My Drive/dataIP/opendata_02_service_ip_66q1.csv

##โหลด DATA

In [12]:
df1 = pd.read_csv(m,dtype={'hcode': str, 'month_no': str})
df1

/tmp/ipykernel_9219/2776323266.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(m,dtype={'hcode': str, 'month_no': str})

,month_no,hcode,hname,province_id,prov,nhso_zonename,gender,service_type,pdx,pdx_name,n_pop,n_service
0,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,R00,Abnormalities of heart beat,1,1
1,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,J44,Other chronic obstructive pulmonary disease,1,1
2,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,R56,Convulsions not elsewhere classified,1,1
3,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,I50,Heart failure,1,1
4,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,R73,Elevated blood glucose level,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
468790,202212,SNC12,รพ.อาภากรเกียรติวงศ์,2000,ชลบุรี,เขต 6 ระยอง,1,IP,F43,Reaction to severe stress and adjustment diso...,1,1
468791,202212,SNC12,รพ.อาภากรเกียรติวงศ์,2000,ชลบุรี,เขต 6 ระยอง,1,IP,F32,Depressive episodes,1,1
468792,202212,SPC02,รพ.จันทรุเบกษา,SP00,กรมแพทย์ทหารอากาศ,กรมแพทย์ทหาร,1,IP,G40,Epilepsy,1,2
468793,202212,SPC02,รพ.จันทรุเบกษา,SP00,กรมแพทย์ทหารอากาศ,กรมแพทย์ทหาร,1,IP,K35,Acute appendicitis,1,1
468794,202212,SPC02,รพ.จันทรุเบกษา,SP00,กรมแพทย์ทหารอากาศ,กรมแพทย์ทหาร,1,IP,R55,Syncope and collapse,1,1

In [13]:
df1.head()

,month_no,hcode,hname,province_id,prov,nhso_zonename,gender,service_type,pdx,pdx_name,n_pop,n_service
0,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,R00,Abnormalities of heart beat,1,1
1,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,J44,Other chronic obstructive pulmonary disease,1,1
2,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,R56,Convulsions not elsewhere classified,1,1
3,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,I50,Heart failure,1,1
4,202210,04007,รพ.ซับใหญ่,3600,ชัยภูมิ,เขต 9 นครราชสีมา,1,IP,R73,Elevated blood glucose level,1,1

In [14]:
df1.isnull().sum()

month_no            0
hcode               0
hname               0
province_id         0
prov                0
nhso_zonename       0
gender              0
service_type        0
pdx                 0
pdx_name         1188
n_pop               0
n_service           0
dtype: int64

In [15]:
# 1. สร้างตารางจับคู่ (รหัสโรค -> ชื่อโรค) จากแถวที่ไม่เป็นค่าว่าง
pdx_dict = df1.dropna(subset=['pdx_name']).drop_duplicates(subset=['pdx']).set_index('pdx')['pdx_name'].to_dict()

# 2. อ่านรหัสโรคจากคอลัมน์ pdx แล้วเอาชื่อโรคมาเติมในช่อง pdx_name ที่ว่าง
df1['pdx_name'] = df1['pdx_name'].fillna(df1['pdx'].map(pdx_dict))

In [16]:
df1.isnull().sum()

month_no            0
hcode               0
hname               0
province_id         0
prov                0
nhso_zonename       0
gender              0
service_type        0
pdx                 0
pdx_name         1188
n_pop               0
n_service           0
dtype: int64

In [17]:
print(f"Original number of rows: {len(df1)}")
df1.dropna(inplace=True)
print(f"Number of rows after dropping nulls: {len(df1)}")

Original number of rows: 468795
Number of rows after dropping nulls: 467607

In [18]:
# แปลงรหัสเพศให้เป็นชื่อที่อ่านเข้าใจง่าย (1: ชาย, 2: หญิง, อื่นๆ: ไม่ระบุ)
df1['gender'] = df1['gender'].fillna(0)
gender_map = {1.0: 'ชาย', 2.0: 'หญิง', 0: 'ไม่ระบุ'}
df1['gender_label'] = df1['gender'].map(gender_map)

Top 5 ผู้ป่วยที่เข้ารับบริการส่วนมากเข้ามารับบริการเพราะโรคใด

In [20]:
import plotly.express as px

# 1. เตรียมข้อมูลสรุปโรคและคำนวณสัดส่วนเปอร์เซ็นต์
df_disease = df1.groupby('pdx_name')['n_service'].sum().reset_index()
total_services = df_disease['n_service'].sum()
df_disease['percentage'] = (df_disease['n_service'] / total_services) * 100
df_disease = df_disease.sort_values(by='n_service', ascending=False)

# 2. ดึง 5 อันดับแรก
top5_disease = df_disease.head(5)

# 3. สร้างกราฟแท่งแนวนอนแสดงโรคที่เด่นที่สุด 5 อันดับแรกพร้อมเปอร์เซ็นต์สัดส่วน
fig = px.bar(
    top5_disease,
    x='n_service',
    y='pdx_name',
    orientation='h',
    text=top5_disease.apply(lambda r: f"{r['n_service']:,} ครั้ง ({r['percentage']:.2f}%)", axis=1),
    color='n_service',
    color_continuous_scale='Reds',
    title='5 อันดับโรค/อาการที่เด่นที่สุดและมีสัดส่วนผู้เข้าใช้บริการสูงที่สุด (Top Dominant Diseases)',
    labels={'pdx_name': 'ชื่อโรค / อาการ', 'n_service': 'จำนวนครั้งการให้บริการ'}
)

fig.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_title="จำนวนครั้งการเข้ารับบริการ (ครั้ง)",
    yaxis_title="",
    coloraxis_showscale=False,
    height=550,
    margin=dict(l=150, r=50, t=80, b=50)
)

fig.update_traces(textposition='inside', textfont=dict(color='white', size=11))
fig.show()

ใช้ Treemap สำหรับแสดงสัดส่วนของโรคจำแนกตามภูมิภาค

In [22]:
import plotly.express as px

# กำหนดจังหวัดในแต่ละภูมิภาคเพื่อแก้ปัญหาไม่มีตัวแปรหรือโมดูล code_context
region_map = {
    # ภาคเหนือ
    'เชียงใหม่': 'ภาคเหนือ', 'เชียงราย': 'ภาคเหนือ', 'ลำปาง': 'ภาคเหนือ', 'ลำพูน': 'ภาคเหนือ',
    'แม่ฮ่องสอน': 'ภาคเหนือ', 'น่าน': 'ภาคเหนือ', 'พะเยา': 'ภาคเหนือ', 'แพร่': 'ภาคเหนือ',
    'อุตรดิตถ์': 'ภาคเหนือ', 'พิษณุโลก': 'ภาคเหนือ', 'สุโขทัย': 'ภาคเหนือ', 'ตาก': 'ภาคเหนือ',
    'สุพรรณบุรี': 'ภาคกลาง', 'พิจิตร': 'ภาคเหนือ', 'เพชรบูรณ์': 'ภาคเหนือ', 'กำแพงเพชร': 'ภาคเหนือ',
    'นครสวรรค์': 'ภาคเหนือ', 'อุทัยธานี': 'ภาคเหนือ',

    # ภาคตะวันออกเฉียงเหนือ
    'ขอนแก่น': 'ภาคตะวันออกเฉียงเหนือ', 'อุดรธานี': 'ภาคตะวันออกเฉียงเหนือ', 'เลย': 'ภาคตะวันออกเฉียงเหนือ',
    'หนองคาย': 'ภาคตะวันออกเฉียงเหนือ', 'หนองบัวลำภู': 'ภาคตะวันออกเฉียงเหนือ', 'บึงกาฬ': 'ภาคตะวันออกเฉียงเหนือ',
    'สกลนคร': 'ภาคตะวันออกเฉียงเหนือ', 'นครพนม': 'ภาคตะวันออกเฉียงเหนือ', 'มุกดาหาร': 'ภาคตะวันออกเฉียงเหนือ',
    'กาฬสินธุ์': 'ภาคตะวันออกเฉียงเหนือ', 'มหาสารคาม': 'ภาคตะวันออกเฉียงเหนือ', 'ร้อยเอ็ด': 'ภาคตะวันออกเฉียงเหนือ',
    'ยโสธร': 'ภาคตะวันออกเฉียงเหนือ', 'อำนาจเจริญ': 'ภาคตะวันออกเฉียงเหนือ', 'นครราชสีมา': 'ภาคตะวันออกเฉียงเหนือ',
    'ชัยภูมิ': 'ภาคตะวันออกเฉียงเหนือ', 'บุรีรัมย์': 'ภาคตะวันออกเฉียงเหนือ', 'สุรินทร์': 'ภาคตะวันออกเฉียงเหนือ',
    'ศรีสะเกษ': 'ภาคตะวันออกเฉียงเหนือ', 'อุบลราชธานี': 'ภาคตะวันออกเฉียงเหนือ',

    # ภาคกลาง
    'กรุงเทพมหานคร': 'ภาคกลาง', 'นนทบุรี': 'ภาคกลาง', 'ปทุมธานี': 'ภาคกลาง', 'สมุทรปราการ': 'ภาคกลาง',
    'นครปฐม': 'ภาคกลาง', 'สมุทรสาคร': 'ภาคกลาง', 'สมุทรสงคราม': 'ภาคกลาง', 'พระนครศรีอยุธยา': 'ภาคกลาง',
    'อ่างทอง': 'ภาคกลาง', 'ลพบุรี': 'ภาคกลาง', 'สิงห์บุรี': 'ภาคกลาง', 'ชัยนาท': 'ภาคกลาง',
    'สระบุรี': 'ภาคกลาง', 'นครนายก': 'ภาคกลาง', 'ปราจีนบุรี': 'ภาคตะวันออก', 'ฉะเชิงเทรา': 'ภาคตะวันออก',
    'สระแก้ว': 'ภาคตะวันออก', 'ชลบุรี': 'ภาคตะวันออก', 'ระยอง': 'ภาคตะวันออก', 'จันทบุรี': 'ภาคตะวันออก',
    'ตราด': 'ภาคตะวันออก', 'กาญจนบุรี': 'ภาคตะวันตก', 'ราชบุรี': 'ภาคตะวันตก', 'เพชรบุรี': 'ภาคตะวันตก',
    'ประจวบคีรีขันธ์': 'ภาคตะวันตก', 'พิษณุโลก': 'ภาคเหนือ',

    # ภาคใต้
    'ชุมพร': 'ภาคใต้', 'ระนอง': 'ภาคใต้', 'สุราษฎร์ธานี': 'ภาคใต้', 'พังงา': 'ภาคใต้',
    'ภูเก็ต': 'ภาคใต้', 'กระบี่': 'ภาคใต้', 'นครศรีธรรมราช': 'ภาคใต้', 'ตรัง': 'ภาคใต้',
    'พัทลุง': 'ภาคใต้', 'สตูล': 'ภาคใต้', 'สงขลา': 'ภาคใต้', 'ปัตตานี': 'ภาคใต้',
    'ยะลา': 'ภาคใต้', 'นราธิวาส': 'ภาคใต้'
}

# แมปคอลัมน์ region
df1['region'] = df1['prov'].map(region_map)
df1['region'] = df1['region'].fillna('ภาคกลาง')

# 1. จัดกลุ่มข้อมูลตามภูมิภาคและชื่อโรค
df_region_disease = df1.groupby(['region', 'pdx_name'], as_index=False)['n_service'].sum()

# 2. ดึง Top 5 โรคของแต่ละภูมิภาค
top_diseases_per_region = df_region_disease.sort_values(['region', 'n_service'], ascending=[True, False]).groupby('region').head(5).reset_index(drop=True)

# 3. สร้าง Treemap
fig = px.treemap(
    top_diseases_per_region,
    path=['region', 'pdx_name'],
    values='n_service',
    color='n_service',
    color_continuous_scale='Purples',
    title='Treemap แสดงสัดส่วนโรคเด่น 5 อันดับแรกจำแนกตามภูมิภาค (ภูมิภาค -> ชื่อโรค)',
    labels={'region': 'ภูมิภาค', 'pdx_name': 'ชื่อโรค/อาการ', 'n_service': 'จำนวนครั้งการบริการ'}
)

# 4. ปรับแต่งการแสดงผล
fig.update_traces(
    root_color="#f0f2f5",
    textinfo="label+value+percent parent",
    textfont=dict(size=13, family="Tohoma, Sans-serif"),
    marker=dict(
        line=dict(color='white', width=2)
    ),
    hovertemplate="""<b>ระดับชั้น:</b> %{label}<br><b>จำนวนครั้งการให้บริการ:</b> %{value:,} ครั้ง<br><b>สัดส่วนจากกลุ่มหลัก:</b> %{percentParent:.2%}<br><b>สัดส่วนจากทั้งหมด:</b> %{percentRoot:.2%}<extra></extra>"""
)

fig.update_layout(
    margin=dict(t=60, l=10, r=10, b=10),
    height=750,
    font=dict(size=12),
    coloraxis_colorbar=dict(
        title="จำนวนครั้ง",
        thickness=15,
        len=0.8
    )
)

fig.show()

ใช้ Marimekko Chart สำหรับแสดงความสัมพันธ์ระหว่างโรคและเพศ

In [23]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

# 1. กรองเฉพาะ Top 10 โรคที่มีผู้ใช้บริการสูงสุดเพื่อไม่ให้กราฟหนาแน่นเกินไป
top10_pdx = df1.groupby('pdx_name')['n_service'].sum().nlargest(10).index
df_filtered = df1[df1['pdx_name'].isin(top10_pdx)]

# 2. คำนวณสรุปข้อมูลแยกตาม โรค และ เพศ
df_grouped_pdx = df_filtered.groupby(['pdx_name', 'gender_label'])['n_service'].sum().unstack(fill_value=0)

# หาผลรวมของแต่ละโรค และสัดส่วนสะสมเพื่อเรียงลำดับจากมากไปน้อย
pdx_totals = df_grouped_pdx.sum(axis=1)
total_pdx_services = pdx_totals.sum()
pdx_shares = (pdx_totals / total_pdx_services).sort_values(ascending=False)

# เรียงลำดับข้อมูล
df_grouped_pdx = df_grouped_pdx.reindex(pdx_shares.index)
df_percentage_pdx = df_grouped_pdx.div(df_grouped_pdx.sum(axis=1), axis=0) * 100

# 3. คำนวณตำแหน่งแกน X และความกว้าง
widths_pdx = pdx_shares.values * 100
x_positions_pdx = np.cumsum(widths_pdx) - (widths_pdx / 2)

# 4. สร้าง Marimekko Chart
fig = go.Figure()
genders = ['ชาย', 'หญิง', 'ไม่ระบุ']
colors_map = {'ชาย': '#3182bd', 'หญิง': '#e377c2', 'ไม่ระบุ': '#7f7f7f'}

for g in genders:
    if g in df_percentage_pdx.columns:
        fig.add_trace(go.Bar(
            name=g,
            x=x_positions_pdx,
            y=df_percentage_pdx[g],
            width=widths_pdx,
            offset=-(widths_pdx / 2),
            marker=dict(color=colors_map.get(g, '#7f7f7f'), line=dict(color='white', width=1.5)),
            customdata=np.stack([
                df_grouped_pdx[g],
                [pdx_totals[p] for p in df_grouped_pdx.index],
                [pdx_shares[p] * 100 for p in df_grouped_pdx.index]
            ], axis=-1),
            hovertemplate=(
                "โรค: %{x_label}" +
                "เพศ: " + g + "" +
                "สัดส่วนเพศในโรคนี้: %{y:.1f}%" +
                "จำนวนการรักษาเฉพาะเพศ: %{customdata[0]:,} ครั้ง" +
                "จำนวนรวมของโรคนี้: %{customdata[1]:,} ครั้ง" +
                "ส่วนแบ่งของโรคนี้ใน Top 10: %{customdata[2]:.1f}%" +
                ""
            )
        ))

fig.update_layout(
    barmode='stack',
    title=dict(
        text='Marimekko Chart: สัดส่วนเพศและขนาดจำนวนการรักษาจำแนกตามกลุ่มโรค (Top 10)(ความกว้างสะท้อนสัดส่วนผู้เข้ารับรักษาของแต่ละโรค / ความสูงสะท้อนสัดส่วนเพศภายในโรคนั้น)',
        x=0.5
    ),
    xaxis=dict(
        title='สัดส่วนการใช้บริการสะสมของกลุ่มโรคหลัก (%)',
        tickvals=list(np.linspace(0, 100, 11)),
        ticktext=[f'{int(val)}%' for val in np.linspace(0, 100, 11)]
    ),
    yaxis=dict(
        title='สัดส่วนของแต่ละเพศ (%)',
        ticksuffix='%'
    ),
    legend_title='เพศ',
    height=750,
    width=1150,
    margin=dict(t=160, b=150, l=80, r=40)
)

# ปรับป้ายกำกับชื่อโรคด้านบนเพื่อป้องกันการซ้อนเบียด
for pdx, x_pos, width in zip(df_grouped_pdx.index, x_positions_pdx, widths_pdx):
    # ตัดคำสั้นลงเพื่อความกระชับและไม่เบียดเสียด
    short_name = pdx[:20] + '...' if len(pdx) > 20 else pdx
    fig.add_annotation(
        x=x_pos,
        y=105,
        text=f"{short_name}({width:.1f}%)",
        showarrow=False,
        font=dict(size=8.5, color='black'),
        align='center',
        textangle=-30 # เอียงองศาเพิ่มขึ้นเพื่อหลบเลี่ยงการซ้อนทับอย่างมีประสิทธิภาพ
    )

fig.show()

สร้างคอลัมน์ภูมิภาคจากข้อมูลจังหวัด
แสดงกราฟข้อมูลจากภูมิภาคไปเขต

In [25]:
# กำหนดจังหวัดในแต่ละภูมิภาค
region_map = {
    # ภาคเหนือ
    'เชียงใหม่': 'ภาคเหนือ',
    'เชียงราย': 'ภาคเหนือ',
    'ลำปาง': 'ภาคเหนือ',
    'ลำพูน': 'ภาคเหนือ',
    'แม่ฮ่องสอน': 'ภาคเหนือ',
    'น่าน': 'ภาคเหนือ',
    'พะเยา': 'ภาคเหนือ',
    'แพร่': 'ภาคเหนือ',
    'อุตรดิตถ์': 'ภาคเหนือ',
    'พิษณุโลก': 'ภาคเหนือ',
    'สุโขทัย': 'ภาคเหนือ',

    # ภาคตะวันออกเฉียงเหนือ
    'ขอนแก่น': 'ภาคตะวันออกเฉียงเหนือ',
    'อุดรธานี': 'ภาคตะวันออกเฉียงเหนือ',
    'เลย': 'ภาคตะวันออกเฉียงเหนือ',
    'หนองคาย': 'ภาคตะวันออกเฉียงเหนือ',
    'หนองบัวลำภู': 'ภาคตะวันออกเฉียงเหนือ',
    'บึงกาฬ': 'ภาคตะวันออกเฉียงเหนือ',
    'สกลนคร': 'ภาคตะวันออกเฉียงเหนือ',
    'นครพนม': 'ภาคตะวันออกเฉียงเหนือ',
    'มุกดาหาร': 'ภาคตะวันออกเฉียงเหนือ',
    'กาฬสินธุ์': 'ภาคตะวันออกเฉียงเหนือ',
    'มหาสารคาม': 'ภาคตะวันออกเฉียงเหนือ',
    'ร้อยเอ็ด': 'ภาคตะวันออกเฉียงเหนือ',
    'ยโสธร': 'ภาคตะวันออกเฉียงเหนือ',
    'อำนาจเจริญ': 'ภาคตะวันออกเฉียงเหนือ',
    'นครราชสีมา': 'ภาคตะวันออกเฉียงเหนือ',
    'ชัยภูมิ': 'ภาคตะวันออกเฉียงเหนือ',
    'บุรีรัมย์': 'ภาคตะวันออกเฉียงเหนือ',
    'สุรินทร์': 'ภาคตะวันออกเฉียงเหนือ',
    'ศรีสะเกษ': 'ภาคตะวันออกเฉียงเหนือ',
    'อุบลราชธานี': 'ภาคตะวันออกเฉียงเหนือ',

    # ภาคกลาง
    'กรุงเทพมหานคร': 'ภาคกลาง',
    'กรุงเทพฯ': 'ภาคกลาง',
    'นครปฐม': 'ภาคกลาง',
    'นนทบุรี': 'ภาคกลาง',
    'ปทุมธานี': 'ภาคกลาง',
    'สมุทรปราการ': 'ภาคกลาง',
    'สมุทรสาคร': 'ภาคกลาง',
    'สมุทรสงคราม': 'ภาคกลาง',
    'พระนครศรีอยุธยา': 'ภาคกลาง',
    'อ่างทอง': 'ภาคกลาง',
    'ลพบุรี': 'ภาคกลาง',
    'สิงห์บุรี': 'ภาคกลาง',
    'ชัยนาท': 'ภาคกลาง',
    'สระบุรี': 'ภาคกลาง',
    'นครสวรรค์': 'ภาคกลาง',
    'อุทัยธานี': 'ภาคกลาง',
    'กำแพงเพชร': 'ภาคกลาง',
    'พิจิตร': 'ภาคกลาง',
    'เพชรบูรณ์': 'ภาคกลาง',
    'สุพรรณบุรี': 'ภาคกลาง',
    'นครนายก': 'ภาคกลาง',

    # ภาคตะวันออก
    'ชลบุรี': 'ภาคตะวันออก',
    'ระยอง': 'ภาคตะวันออก',
    'จันทบุรี': 'ภาคตะวันออก',
    'ตราด': 'ภาคตะวันออก',
    'ฉะเชิงเทรา': 'ภาคตะวันออก',
    'ปราจีนบุรี': 'ภาคตะวันออก',
    'สระแก้ว': 'ภาคตะวันออก',

    # ภาคตะวันตก
    'กาญจนบุรี': 'ภาคตะวันตก',
    'ราชบุรี': 'ภาคตะวันตก',
    'เพชรบุรี': 'ภาคตะวันตก',
    'ประจวบคีรีขันธ์': 'ภาคตะวันตก',
    'ตาก': 'ภาคตะวันตก',

    # ภาคใต้
    'ชุมพร': 'ภาคใต้',
    'ระนอง': 'ภาคใต้',
    'สุราษฎร์ธานี': 'ภาคใต้',
    'พังงา': 'ภาคใต้',
    'ภูเก็ต': 'ภาคใต้',
    'กระบี่': 'ภาคใต้',
    'นครศรีธรรมราช': 'ภาคใต้',
    'ตรัง': 'ภาคใต้',
    'พัทลุง': 'ภาคใต้',
    'สตูล': 'ภาคใต้',
    'สงขลา': 'ภาคใต้',
    'ปัตตานี': 'ภาคใต้',
    'ยะลา': 'ภาคใต้',
    'นราธิวาส': 'ภาคใต้'
}

# สร้างคอลัมน์ภูมิภาคจากจังหวัด
df1['region'] = df1['prov'].map(region_map)


# =========================================================
# จัดกลุ่มข้อมูลกรมแพทย์ทหารเข้า "ภูมิภาค"
# =========================================================

# กรมแพทย์ทหารเรือ
# รพ.ทหารเรือกรุงเทพ → ภาคกลาง
df1.loc[
    (df1['prov'] == 'กรมแพทย์ทหารเรือ') &
    (df1['hname'].str.contains('รพ.ทหารเรือกรุงเทพ', na=False)),
    'region'
] = 'ภาคกลาง'

# หน่วยกรมแพทย์ทหารเรือที่อยู่ชลบุรี → ภาคตะวันออก
df1.loc[
    (df1['prov'] == 'กรมแพทย์ทหารเรือ') &
    (df1['hname'].str.contains(
        'ศูนย์ฝึกทหารใหม่|รร.ชุมพลฯ|กองพันพยาบาลกรมสนับสนุนหน่วยบัญชาการต่อสู้อากาศยาน',
        na=False
    )),
    'region'
] = 'ภาคตะวันออก'

# หน่วยที่เกี่ยวข้องกับจันทบุรีและตราด → ภาคตะวันออก
df1.loc[
    (df1['prov'] == 'กรมแพทย์ทหารเรือ') &
    (df1['hname'].str.contains('จันทบุรีและตราด', na=False)),
    'region'
] = 'ภาคตะวันออก'


# กรมแพทย์ทหารอากาศ
# รพ.จันทรุเบกษา → ภาคกลาง
df1.loc[
    (df1['prov'] == 'กรมแพทย์ทหารอากาศ') &
    (df1['hname'].str.contains('รพ.จันทรุเบกษา', na=False)),
    'region'
] = 'ภาคกลาง'


# =========================================================
# ตรวจสอบผล
# =========================================================

print("===== ตรวจสอบข้อมูลที่ยังไม่มีภูมิภาค =====")

missing_region = df1[df1['region'].isna()]

print("จำนวนข้อมูลที่ยังไม่มีภูมิภาค:", len(missing_region))

if len(missing_region) > 0:
    display(
        missing_region[
            ['prov', 'hname', 'hcode', 'region']
        ].drop_duplicates()
    )

print("\n===== จำนวนข้อมูลในแต่ละภูมิภาค =====")

display(
    df1['region']
    .value_counts(dropna=False)
    .rename_axis('region')
    .reset_index(name='count')
)

===== ตรวจสอบข้อมูลที่ยังไม่มีภูมิภาค =====
จำนวนข้อมูลที่ยังไม่มีภูมิภาค: 0

===== จำนวนข้อมูลในแต่ละภูมิภาค =====

                  region   count
0  ภาคตะวันออกเฉียงเหนือ  163833
1                ภาคกลาง  108489
2                 ภาคใต้   73735
3               ภาคเหนือ   64584
4            ภาคตะวันออก   32058
5             ภาคตะวันตก   24908

In [27]:
print("การกระจายของข้อมูลตามภูมิภาค:")
display(df1['region'].value_counts())

การกระจายของข้อมูลตามภูมิภาค:

region
ภาคตะวันออกเฉียงเหนือ    163833
ภาคกลาง                  108489
ภาคใต้                    73735
ภาคเหนือ                  64584
ภาคตะวันออก               32058
ภาคตะวันตก                24908
Name: count, dtype: int64

In [29]:
import plotly.express as px

# 3. จัดกลุ่มข้อมูลเฉพาะ 2 ระดับ (ภูมิภาค -> เขต สปสช.)
df_tree = df1.groupby(['region', 'nhso_zonename'], as_index=False)['n_service'].sum()

# 4. สร้าง Treemap (2 ชั้น)
fig = px.treemap(
    df_tree,
    path=['region', 'nhso_zonename'], # ปรับเหลือ 2 ระดับ
    values='n_service',
    color='n_service',
    color_continuous_scale='Blues',
    title='Treemap แสดงสัดส่วนการใช้บริการสุขภาพ (ภูมิภาค -> เขต สปสช.)'
)

fig.update_traces(root_color="lightgrey")
fig.update_layout(margin=dict(t=50, l=10, r=10, b=10))

# แสดงผลแผนภูมิ
fig.show()

ภูมิภาคไหนที่มีคนเข้าใช้บริการบ่อยที่สุด

In [30]:
import plotly.express as px

# คำนวณสรุปจำนวนครั้งการรับบริการตามภูมิภาคจาก df4
df_region = df1.groupby('region')['n_service'].sum().reset_index()

# เรียงลำดับจากมากไปน้อย
df_region = df_region.sort_values(by='n_service', ascending=False)

# สร้างกราฟแท่ง
fig = px.bar(
    df_region,
    x='region',
    y='n_service',
    text='n_service',
    color='n_service',
    color_continuous_scale='Blues',
    title='จำนวนการเข้าใช้บริการสุขภาพจำแนกตามภูมิภาค',
    labels={'region': 'ภูมิภาค', 'n_service': 'จำนวนครั้งรับบริการ'}
)
fig.update_traces(texttemplate='%{text:,}', textposition='outside')
fig.update_layout(xaxis={'categoryorder':'total descending'})
fig.show()

แสดงเขตไปจังหวัด

In [32]:
df_tree = df1.groupby(['nhso_zonename', 'prov'], as_index=False)['n_service'].sum()

fig = px.treemap(
    df_tree,
    path=['nhso_zonename', 'prov'],    # ลำดับชั้น Hierarchy (เขต สปสช. -> จังหวัด)
    values='n_service',                 # ขนาดบล็อกตามจำนวนการบริการ
    color='n_service',                  # ความเข้มสีตามจำนวนบริการ
    color_continuous_scale='Blues',     # ชุดสีโทนฟ้า
    title='Treemap แสดงสัดส่วนการใช้บริการสุขภาพ (เขต สปสช. -> จังหวัด)'
)

fig.update_traces(root_color="lightgrey")
fig.update_layout(margin=dict(t=50, l=10, r=10, b=10))

fig.show()

แบ่งเพศชายหญิง

In [33]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go

# 1. เตรียมและคำนวณข้อมูลสำหรับ Marimekko Chart
# หาจำนวนรวมของบริการแบ่งตาม ภูมิภาค และ เพศ
df_grouped = df1.groupby(['region', 'gender_label'])['n_service'].sum().unstack(fill_value=0)

# หาผลรวมบริการรวมของแต่ละภูมิภาค และ สัดส่วนรวมของแต่ละภูมิภาคในประเทศ
region_totals = df_grouped.sum(axis=1)
total_services = region_totals.sum()
region_shares = (region_totals / total_services).sort_values(ascending=False)

# เรียงลำดับภูมิภาคตามขนาดจำนวนครั้งรับบริการจากมากไปน้อย
df_grouped = df_grouped.reindex(region_shares.index)

# แปลงข้อมูลจำนวนบริการในแต่ละภูมิภาคให้เป็นเปอร์เซ็นต์ (สัดส่วน 100% ภายในกลุ่ม)
df_percentage = df_grouped.div(df_grouped.sum(axis=1), axis=0) * 100

# 2. คำนวณตำแหน่งและสเกลความกว้างของแต่ละแท่งบนแกน X
widths = region_shares.values * 100  # แปลงสัดส่วนความกว้างเป็น % 0-100
x_positions = np.cumsum(widths) - (widths / 2)  # จุดกึ่งกลางของแต่ละแท่งสำหรับวางป้ายชื่อ

# 3. สร้างกราฟ Marimekko โดยใช้ go.Bar
fig = go.Figure()

# เพิ่มแท่งกราฟสำหรับแต่ละเพศ
genders = df_percentage.columns
colors = {'ชาย': '#3182bd', 'หญิง': '#e377c2', 'ไม่ระบุ': '#7f7f7f'}  # กำหนดโทนสี

for gender in genders:
    fig.add_trace(go.Bar(
        name=gender,
        x=x_positions,
        y=df_percentage[gender],
        width=widths, # กำหนดความกว้างของแท่งตามส่วนแบ่งของภูมิภาค
        offset=-(widths/2), # จัดแนวให้อยู่ตรงกลางตำแหน่ง x
        marker=dict(color=colors.get(gender, '#bcbd22'), line=dict(color='white', width=1.5)),
        customdata=np.stack([
            df_grouped[gender],
            [region_totals[r] for r in df_grouped.index],
            [region_shares[r]*100 for r in df_grouped.index]
        ], axis=-1),
        hovertemplate=(
            "ภูมิภาค: %{x_label}" +
            "เพศ: " + gender + "" +
            "สัดส่วนเพศในภูมิภาคนี้: %{y:.1f}%" +
            "จำนวนบริการเฉพาะเพศนี้: %{customdata[0]:,}" +
            "บริการทั้งหมดของภูมิภาคนี้: %{customdata[1]:,}" +
            "ส่วนแบ่งของภูมิภาคในประเทศ: %{customdata[2]:.1f}%" +
            ""
        )
    ))

# 4. ตั้งค่าหน้าตากราฟและแสดงผล
fig.update_layout(
    barmode='stack',
    title=dict(
        text='Marimekko Chart: สัดส่วนเพศและขนาดจำนวนผู้รับบริการจำแนกตามภูมิภาค(ความกว้างแท่งสะท้อนส่วนแบ่งผู้รับบริการของแต่ละภูมิภาค / ความสูงสะท้อนสัดส่วนเพศในภูมิภาคนั้น)',
        x=0.5
    ),
    xaxis=dict(
        title='สัดส่วนจำนวนบริการสะสมของภูมิภาค (%)',
        tickvals=list(np.linspace(0, 100, 11)),
        ticktext=[f'{int(val)}%' for val in np.linspace(0, 100, 11)]
    ),
    yaxis=dict(
        title='สัดส่วนของเพศ (%)',
        ticksuffix='%'
    ),
    legend_title='เพศ',
    height=700,
    width=1100,
    margin=dict(t=140, b=100, l=80, r=40)
)

# เพิ่มป้ายชื่อภูมิภาคที่แกน X ด้านบนตัวกราฟแบบเฉียงเพื่อกันตัวหนังสือเบียดกัน
for region, x_pos, width in zip(df_grouped.index, x_positions, widths):
    fig.add_annotation(
        x=x_pos,
        y=105,
        text=f"{region}({width:.1f}%)",
        showarrow=False,
        font=dict(size=10, color='black'),
        align='center',
        textangle=-15 # เอียงหลบเพื่อป้องกันตัวหนังสือซ้อนกัน
    )

fig.show()

In [34]:
import pandas as pd
import plotly.express as px

# หา 5 อันดับแรกของโรงพยาบาลที่มีจำนวนครั้งการบริการสูงสุด
top5_hospitals = df1.groupby('hname')['n_service'].sum().nlargest(5).reset_index()

# แสดงเป็นกราฟแท่งเพื่อให้อ่านง่าย
fig = px.bar(
    top5_hospitals,
    x='n_service',
    y='hname',
    orientation='h',
    text='n_service',
    color='n_service',
    color_continuous_scale='Blues',
    title='5 อันดับโรงพยาบาลที่มีจำนวนครั้งการให้บริการสูงสุด',
    labels={'n_service': 'จำนวนครั้งการให้บริการ', 'hname': 'ชื่อโรงพยาบาล'}
)

fig.update_traces(texttemplate='%{text:,}', textposition='outside')
fig.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    xaxis_title="จำนวนครั้งการให้บริการ",
    yaxis_title="",
    coloraxis_showscale=False,
    margin=dict(l=250, r=50, t=80, b=50)
)
fig.show()

In [36]:
# ดึงข้อมูล 5 อันดับแรกที่มีจำนวนครั้งการบริการ (n_service) สูงที่สุด
top5_cases = df1.nlargest(5, 'n_service')[['month_no', 'hname', 'prov', 'gender_label', 'pdx_name', 'n_service']]

print("ข้อมูล 5 กลุ่มผู้เข้าใช้บริการ (หรือ 5 ราย) ที่มีจำนวนครั้งการเข้าใช้บริการสูงสุด:")
display(top5_cases.style.format({'n_service': '{:,}'}))

ข้อมูล 5 กลุ่มผู้เข้าใช้บริการ (หรือ 5 ราย) ที่มีจำนวนครั้งการเข้าใช้บริการสูงสุด:

ใช้ Nightingale Rose Chart สำหรับแสดงการกระจายของผู้ป่วยในแต่ละเดือน

In [37]:
import plotly.express as px
import pandas as pd

# จัดกลุ่มข้อมูลตาม เดือน (month_no) และ เพศ (gender_label) เพื่อหาผลรวมจำนวนบริการ
df_monthly_gender = df1.groupby(['month_no', 'gender_label'])['n_service'].sum().reset_index()

# แปลงรหัสเดือนให้เป็นชื่อเดือนที่เข้าใจง่าย
month_map = {
    '202307': 'กรกฎาคม 2023',
    '202308': 'สิงหาคม 2023',
    '202309': 'กันยายน 2023'
}
df_monthly_gender['month_name'] = df_monthly_gender['month_no'].astype(str).map(month_map).fillna(df_monthly_gender['month_no'])

# เรียงลำดับข้อมูลตามรหัสเดือน
df_monthly_gender = df_monthly_gender.sort_values('month_no')

# สร้าง Rose Chart (Polar Bar Chart) โดยใช้ px.bar_polar และแก้ barmode เป็น 'stack'
fig = px.bar_polar(
    df_monthly_gender,
    r='n_service',
    theta='month_name',
    color='gender_label',
    color_discrete_map={'ชาย': '#3182bd', 'หญิง': '#e377c2', 'ไม่ระบุ': '#7f7f7f'},
    barmode='stack',
    title='จำนวนการเข้าใช้บริการจำแนกตามเพศในแต่ละเดือน',
    labels={'n_service': 'จำนวนครั้งการให้บริการ', 'month_name': 'เดือน', 'gender_label': 'เพศ'}
)

# ปรับแต่งการแสดงผลและป้ายข้อความ
fig.update_layout(
    polar=dict(
        angularaxis=dict(direction='clockwise', period=len(df_monthly_gender['month_name'].unique())),
        radialaxis=dict(ticksuffix='', angle=45)
    ),
    font=dict(size=12),
    height=600,
    width=800
)

fig.show()

ใช้ Stacked Area Chart สำหรับเปรียบเทียบแนวโน้มของโรคในแต่ละภูมิภาค

In [43]:
import pandas as pd
import plotly.express as px

# 1. เตรียมข้อมูล
df_plot = df1[['region', 'pdx_name', 'n_service']].copy()

# 2. ทำความสะอาดข้อมูล
df_plot['n_service'] = pd.to_numeric(
    df_plot['n_service'], errors='coerce'
)

df_plot = df_plot.dropna(
    subset=['region', 'pdx_name', 'n_service']
)

# 3. หา Top 5 โรค
top_diseases = (
    df_plot.groupby('pdx_name')['n_service']
    .sum()
    .nlargest(5)
    .index
)

# 4. กรองข้อมูล Top 5 และรวมจำนวนบริการ
df_area = df_plot[
    df_plot['pdx_name'].isin(top_diseases)
].groupby(
    ['region', 'pdx_name'], as_index=False
)['n_service'].sum()

# 5. เรียงภูมิภาค
region_order = [
    'เหนือ', 'ตะวันออกเฉียงเหนือ', 'กลาง',
    'ตะวันออก', 'ตะวันตก', 'ใต้', 'อื่น ๆ'
]

# แปลงเป็นข้อความก่อนจัดลำดับ
df_area['region'] = df_area['region'].astype(str)

# เรียงตามลำดับที่กำหนด โดยภูมิภาคอื่นจะอยู่ท้าย
order = [r for r in region_order if r in df_area['region'].unique()]
order += [r for r in df_area['region'].unique() if r not in order]

print("จำนวนแถวที่ใช้วาดกราฟ:", len(df_area))
print(df_area.head(10))

# 6. สร้างกราฟแท่งแบบกลุ่ม
fig = px.bar(
    df_area,
    x='region',
    y='n_service',
    color='pdx_name',
    barmode='group',
    category_orders={'region': order},
    title='Top 5 โรคที่มีจำนวนการให้บริการสูงสุด จำแนกตามภูมิภาค',
    labels={
        'region': 'ภูมิภาค',
        'n_service': 'จำนวนครั้งการให้บริการ',
        'pdx_name': 'โรค/อาการ'
    },
    color_discrete_sequence=px.colors.qualitative.Safe,
    template='plotly_white'
)

fig.update_layout(
    xaxis_title='ภูมิภาค',
    yaxis_title='จำนวนครั้งการให้บริการ (ครั้ง)',
    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=1.02,
        xanchor='center',
        x=0.5
    )
)

fig.show()

จำนวนแถวที่ใช้วาดกราฟ: 30
       region                                           pdx_name  n_service
0     ภาคกลาง  Diarrhoea and gastroenteritis of presumed infe...       9741
1     ภาคกลาง                                      Heart failure       8459
2     ภาคกลาง        Other chronic obstructive pulmonary disease       5080
3     ภาคกลาง                    Pneumonia  organism unspecified      10347
4     ภาคกลาง                                    Senile cataract      13217
5  ภาคตะวันตก  Diarrhoea and gastroenteritis of presumed infe...       2764
6  ภาคตะวันตก                                      Heart failure       1918
7  ภาคตะวันตก        Other chronic obstructive pulmonary disease       1730
8  ภาคตะวันตก                    Pneumonia  organism unspecified       2591
9  ภาคตะวันตก                                    Senile cataract       2311

วิเคราะห์หาชื่อโรค/อาการที่โดดเด่นและมีผู้เข้าใช้บริการมากที่สุด

In [41]:
import pandas as pd
import plotly.express as px

# 1. จัดกลุ่มและคำนวณผลรวมจำนวนครั้งการรับบริการ (n_service) แยกตามชื่อโรค (pdx_name)
df_disease = df1.groupby('pdx_name')['n_service'].sum().reset_index()

# 2. เรียงลำดับจากมากไปน้อย และคำนวณสัดส่วนสะสม (% Share)
total_all_services = df_disease['n_service'].sum()
df_disease['percentage'] = (df_disease['n_service'] / total_all_services) * 100
df_disease = df_disease.sort_values(by='n_service', ascending=False).reset_index(drop=True)

# ดึง Top 15 โรค/อาการที่เด่นที่สุด
top15_disease = df_disease.head(15)

# แสดงตารางวิเคราะห์
print("ตารางแสดง 15 อันดับโรค/อาการที่เด่นที่สุด (มีสัดส่วนผู้รับบริการสูงที่สุด):")
display(top15_disease.style.format({'n_service': '{:,}', 'percentage': '{:.2f}%'}))

ตารางแสดง 15 อันดับโรค/อาการที่เด่นที่สุด (มีสัดส่วนผู้รับบริการสูงที่สุด):

In [42]:
import plotly.graph_objects as go

# เรียงจากน้อย → มาก
df_lollipop = top15_disease.sort_values('n_service').copy()

# สีพาสเทล 15 สี
pastel_colors = [
    '#A8D8EA',  # ฟ้า
    '#F7B7D2',  # ชมพู
    '#B8E0D2',  # เขียวมิ้นต์
    '#FFD6A5',  # ส้มอ่อน
    '#CDB4DB',  # ม่วง
    '#FFF1A8',  # เหลือง
    '#AFCBFF',  # น้ำเงินอ่อน
    '#FFB7B2',  # แดงพาสเทล
    '#BDE0FE',  # ฟ้าอ่อน
    '#CDEAC0',  # เขียวอ่อน
    '#E2C2FF',  # ม่วงอ่อน
    '#FFD1DC',  # ชมพูอ่อน
    '#B5EAD7',  # เขียวมิ้นต์อ่อน
    '#FFDAC1',  # พีช
    '#D7BDE2'   # ม่วงลาเวนเดอร์
]

fig = go.Figure()

# วาดเส้นและจุดของแต่ละโรค
for i, (_, row) in enumerate(df_lollipop.iterrows()):

    # เส้น
    fig.add_trace(
        go.Scatter(
            x=[0, row['n_service']],
            y=[row['pdx_name'], row['pdx_name']],
            mode='lines',
            line=dict(
                color=pastel_colors[i],
                width=5
            ),
            showlegend=False,
            hoverinfo='skip'
        )
    )

    # จุด
    fig.add_trace(
        go.Scatter(
            x=[row['n_service']],
            y=[row['pdx_name']],
            mode='markers+text',
            marker=dict(
                size=15,
                color=pastel_colors[i],
                line=dict(
                    color='white',
                    width=2
                )
            ),
            text=[f"{row['n_service']:,}"],
            textposition='middle right',
            textfont=dict(
                size=11,
                color='#555555'
            ),
            showlegend=False,
            hovertemplate=(
                '%{y}'
                'จำนวนครั้งเข้ารับบริการ: %{x:,}'
                ''
            )
        )
    )

fig.update_layout(
    title=dict(
        text='15 อันดับโรค/อาการที่มีจำนวนครั้งเข้ารับบริการสูงที่สุด',
        x=0.5
    ),
    xaxis_title='จำนวนครั้งเข้ารับบริการ',
    yaxis_title='โรค/อาการ',

    height=700,

    margin=dict(
        l=300,
        r=100,
        t=90,
        b=60
    ),

    plot_bgcolor='white',
    paper_bgcolor='white',

    xaxis=dict(
        showgrid=True,
        gridcolor='#EEEEEE'
    ),

    yaxis=dict(
        showgrid=False
    )
)

fig.show()